trigger:
- master

pr:
- master

strategy:
  matrix:
    stable:
      rustup_toolchain: 1.32.0
    beta:
      rustup_toolchain: beta
    nightly:
      rustup_toolchain: nightly

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    sudo apt-get update
    sudo apt-get install libsdl2-dev libasound2-dev
  displayName: Install native dependencies
- script: |
    curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $RUSTUP_TOOLCHAIN
    echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
  displayName: Install Rust
- script: cargo test --all
  displayName: Run tests via Cargo
