[package]
name = "tetra"
description = "A simple 2D game framework written in Rust"
version = "0.1.0"
authors = ["Joe Clay <27cupsofcoffee@gmail.com>"]
license = "MIT"
repository = "https://github.com/17cupsofcoffee/tetra"
keywords = ["game framework", "game engine", "gamedev"]
categories = ["game-engines"]

[dependencies]
gl = "0.10.0"
sdl2 = "0.31.0"
image = "0.20.0"
nalgebra-glm = "0.1.3"
fnv = "1.0.3"

[dev-dependencies]
rand = "0.5"