[package]
name = "tetra"
description = "A simple 2D game framework written in Rust"
version = "0.1.6"
authors = ["Joe Clay <27cupsofcoffee@gmail.com>"]
license = "MIT"
repository = "https://github.com/17cupsofcoffee/tetra"
documentation = "https://docs.rs/tetra"
readme = "README.md"
keywords = ["game", "engine", "framework", "gamedev"]
categories = ["game-engines"]
edition = "2018"

[features]
sdl2_bundled = ["sdl2/bundled"]
sdl2_static_link = ["sdl2/static-link"]

[dependencies]
gl = "0.11.0"
sdl2 = "0.32.0"
image = "0.20.1"
nalgebra-glm = "0.2.0"
fnv = "1.0.6"
glyph_brush = "0.2.2"

[dev-dependencies]
rand = "0.6"
rand_core = "0.2.2" # workaround, see https://github.com/rust-random/rand/issues/645
