[package]
name = "tetra"
description = "A simple 2D game framework written in Rust"
version = "0.3.2"
edition = "2018"
authors = ["Joe Clay <27cupsofcoffee@gmail.com>"]
license = "MIT"
repository = "https://github.com/17cupsofcoffee/tetra"
documentation = "https://docs.rs/tetra"
readme = "README.md"
keywords = ["game", "engine", "framework", "gamedev"]
categories = ["game-engines"]

[features]
sdl2_bundled = ["sdl2/bundled"]
sdl2_static_link = ["sdl2/static-link"]
serde_support = ["serde", "vek/serde"]

[dependencies]
sdl2 = "0.32"
rodio = "0.10"
glow = "0.4"
image = "0.22"
vek = { version = "0.9", default-features = false }
hashbrown = "0.6"
glyph_brush = "0.6"
serde = { version = "1.0", optional = true } 

[dev-dependencies]
rand = "0.7"
