[package]
name = "tetra"
description = "A simple 2D game framework written in Rust"
version = "0.2.20"
edition = "2018"
authors = ["Joe Clay <27cupsofcoffee@gmail.com>"]
license = "MIT"
repository = "https://github.com/17cupsofcoffee/tetra"
documentation = "https://docs.rs/tetra"
readme = "README.md"
keywords = ["game", "engine", "framework", "gamedev"]
categories = ["game-engines"]

[features]
sdl2_bundled = ["sdl2/bundled"]
sdl2_static_link = ["sdl2/static-link"]

[dependencies]
glow = "0.2.3"
image = "0.22.1"
nalgebra-glm = "0.4.0"
hashbrown = "0.6.0"
glyph_brush = "0.6.0"
instant = { git = "https://github.com/sebcrozet/instant", features = ["now", "wasm-bindgen"] }

[dev-dependencies]
rand = { version = "0.7", features = ["wasm-bindgen"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
sdl2 = "0.32.2"
rodio = "0.9.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.50"
console_error_panic_hook = "0.1.6"

[target.'cfg(target_arch = "wasm32")'.dependencies.web-sys]
version = "0.3.27"
features = [
    "Document",
    "Element",
    "HtmlCanvasElement",
    "WebGlBuffer",
    "WebGlRenderingContext",
    "WebGlProgram",
    "WebGlShader",
    "Window",
    "console",
    "KeyboardEvent",
    "EventTarget"
]
