blank_issues_enabled: true
contact_links:
  - name: "Discord: Game Development in Rust"
    url: https://discord.gg/yNtPTb2
    about: "For discussion of game development in Rust, and showing off your projects"
  - name: "Discord: Rust Community"
    url: https://bit.ly/rust-community
    about: "For general Rust-related discussion - there is also a #games-and-graphics channel"
