blank_issues_enabled: true
contact_links:
  - name: "Discussions"
    url: https://github.com/17cupsofcoffee/tetra/discussions
    about: "For questions, discussions and project feedback, visit the Discussions tab."
  - name: "Discord"
    url: https://discord.gg/yNtPTb2
    about: "For real-time discussion, visit the Game Development in Rust Discord server."
