name: CI Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [1.36.0, beta, nightly]
    steps:
    - name: Install native dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libsdl2-dev libasound2-dev
    - name: Install Rust toolchains
      run: |
        rustup default ${{ matrix.rust }}
        rustup update ${{ matrix.rust }}
        rustup target add wasm32-unknown-unknown
    - uses: actions/checkout@v1
    - name: Run tests
      run: cargo test --verbose --all
    - name: Run WASM build
      run: cargo build --verbose --all-targets --target wasm32-unknown-unknown
